export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>LinkStreaming</title>
  <base href="https://isaqueemartins.github.io/link-streaming/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<style>*{margin:0;padding:0;box-sizing:border-box}body{background-color:#012a4a}
</style><link rel="stylesheet" href="styles-P4NWQHPI.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles-P4NWQHPI.css"></noscript><style ng-app-id="ng">app-new-link[_ngcontent-ng-c2023778120]{display:flex;align-items:center;justify-content:center;height:90vh}.main-section[_ngcontent-ng-c2023778120]{display:flex;align-items:center;justify-content:center;height:90vh}</style><style ng-app-id="ng">.app-header[_ngcontent-ng-c2498387137]{display:flex;align-items:center;justify-content:center;height:10svh;width:100%}h1[_ngcontent-ng-c2498387137]{color:#fff;font-family:Poppins,sans-serif}</style><style ng-app-id="ng">.app-carousel[_ngcontent-ng-c1479537149]{background-color:#013a63;border-radius:3rem}.link-carousel[_ngcontent-ng-c1479537149]{display:flex;align-items:center;flex-direction:row}.card[_ngcontent-ng-c1479537149]{margin:3rem;cursor:pointer;transition:transform .2s ease}.card[_ngcontent-ng-c1479537149]:hover{transform:scale(1.6)}.overlay[_ngcontent-ng-c1479537149]{position:fixed;top:0;left:0;width:100vw;height:100vh;background-color:#00000080;display:flex;align-items:center;justify-content:center;z-index:1000}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["click"],[]);</script>
  <app-root ng-version="19.2.10" ngh="2" ng-server-context="ssg"><router-outlet></router-outlet><app-home _nghost-ng-c2023778120 ngh="0"><app-header _ngcontent-ng-c2023778120 _nghost-ng-c2498387137 ngh="0"><header _ngcontent-ng-c2498387137 class="app-header"><h1 _ngcontent-ng-c2498387137>Link Streaming</h1></header></app-header><main _ngcontent-ng-c2023778120><section _ngcontent-ng-c2023778120 class="main-section"><app-link-carousel _ngcontent-ng-c2023778120 _nghost-ng-c1479537149 ngh="1"><section _ngcontent-ng-c1479537149 class="app-carousel"><div _ngcontent-ng-c1479537149 class="link-carousel"><div _ngcontent-ng-c1479537149 class="card"><img _ngcontent-ng-c1479537149 ngsrc="/assets/icons8-amazon-prime-video-240.png" width="200" height="200" alt="Prime Video" loading="lazy" fetchpriority="auto" ng-img="true" src="/assets/icons8-amazon-prime-video-240.png" jsaction="click:;"></div><div _ngcontent-ng-c1479537149 class="card"><img _ngcontent-ng-c1479537149 ngsrc="/assets/Netflix_Logo_RGB.png" width="200" height="200" alt="Netflix" loading="lazy" fetchpriority="auto" ng-img="true" src="/assets/Netflix_Logo_RGB.png" jsaction="click:;"></div><div _ngcontent-ng-c1479537149 class="card"><img _ngcontent-ng-c1479537149 ngsrc="/assets/icons8-hbo-max-250.png" width="200" height="200" alt="Hbo Max" loading="lazy" fetchpriority="auto" ng-img="true" src="/assets/icons8-hbo-max-250.png" jsaction="click:;"></div><div _ngcontent-ng-c1479537149 class="card"><img _ngcontent-ng-c1479537149 ngsrc="/assets/mais.png" width="100" height="100" alt="Adicionar Serviço" loading="lazy" fetchpriority="auto" ng-img="true" src="/assets/mais.png" jsaction="click:;"></div></div><!----></section></app-link-carousel></section></main></app-home><!----></app-root>
<script src="polyfills-FFHMD2TL.js" type="module"></script><script src="main-U57WPPWJ.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{},{"t":{"10":"t0"},"c":{"10":[]}},{"c":{"0":[{"i":"c2023778120","r":1}]}}]}</script></body></html>`;